services:
  postgres:
    image: postgres:16
    container_name: neurocards-db
    environment:
      POSTGRES_DB: neurocards
      POSTGRES_USER: kamal
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"